import type { Metadata } from 'next';
import './globals.css';
import { fontCalSans, inter, roboto_mono } from '../../public/assets/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontCalSans.variable} ${inter.variable} ${roboto_mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
